// Sample Data for Products, Users, and Orders
// Use this to populate your MongoDB database

export const productData = [
  {
    name: "Organic Baby Spinach",
    price: 3.99,
    description:
      "Tender organic baby spinach, triple-washed and ready to cook or toss into salads.",
    images: [
      "https://images.unsplash.com/photo-1506806732259-39c2d0268443?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Fresh Vegetables",
    subCategory: "Organic",
    unit: "pack",
    sizes: ["150g", "300g", "500g"],
    nutritionInfo: {
      calories: 23,
      protein: "2.9g",
      carbs: "3.6g",
      fat: "0.4g",
    },
    origin: "Local farms",
    shelfLife: "3-5 days chilled",
    isOrganic: true,
    bestseller: true,
    inStock: true,
    stockQuantity: 120,
    date: Date.now(),
  },
  {
    name: "Roma Tomatoes",
    price: 2.49,
    description:
      "Juicy Roma tomatoes perfect for sauces, salads, and roasting.",
    images: [
      "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Fresh Vegetables",
    subCategory: "Regular",
    unit: "kg",
    sizes: ["500g", "1kg", "2kg"],
    nutritionInfo: {
      calories: 18,
      protein: "0.9g",
      carbs: "3.9g",
      fat: "0.2g",
    },
    origin: "Mexico",
    shelfLife: "5-7 days chilled",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 200,
    date: Date.now(),
  },
  {
    name: "Alphonso Mangoes",
    price: 12.99,
    description:
      "Sweet, fragrant Alphonso mangoes — the king of fruits in season.",
    images: [
      "https://images.unsplash.com/photo-1615485737455-9f8553c9f523?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Fresh Fruits",
    subCategory: "Premium",
    unit: "kg",
    sizes: ["1kg box", "2kg box"],
    nutritionInfo: {
      calories: 60,
      protein: "0.8g",
      carbs: "15g",
      fat: "0.4g",
    },
    origin: "Ratnagiri, India",
    shelfLife: "3-4 days at room temp",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 80,
    date: Date.now(),
  },
  {
    name: "Blueberry Clamshell",
    price: 4.99,
    description:
      "Fresh blueberries packed with antioxidants, perfect for snacking and smoothies.",
    images: [
      "https://images.unsplash.com/photo-1502744688674-c619d1586c9a?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Fresh Fruits",
    subCategory: "Berries",
    unit: "pack",
    sizes: ["125g", "250g"],
    nutritionInfo: {
      calories: 57,
      protein: "0.7g",
      carbs: "14g",
      fat: "0.3g",
    },
    origin: "Chile",
    shelfLife: "5-7 days chilled",
    isOrganic: false,
    bestseller: false,
    inStock: true,
    stockQuantity: 150,
    date: Date.now(),
  },
  {
    name: "A2 Cow Milk",
    price: 2.79,
    description:
      "Fresh A2 cow milk, homogenized and pasteurized for daily nutrition.",
    images: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Dairy Products",
    subCategory: "Milk",
    unit: "liter",
    sizes: ["500ml", "1L", "2L"],
    nutritionInfo: {
      calories: 61,
      protein: "3.2g",
      carbs: "4.8g",
      fat: "3.3g",
    },
    origin: "Local dairy",
    shelfLife: "4-5 days chilled",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 300,
    date: Date.now(),
  },
  {
    name: "Greek Yogurt",
    price: 5.49,
    description:
      "Thick and creamy Greek yogurt with live cultures, perfect for breakfast bowls.",
    images: [
      "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Dairy Products",
    subCategory: "Yogurt",
    unit: "pack",
    sizes: ["170g", "500g"],
    nutritionInfo: {
      calories: 59,
      protein: "10g",
      carbs: "3.6g",
      fat: "0.4g",
    },
    origin: "USA",
    shelfLife: "10-14 days chilled",
    isOrganic: true,
    bestseller: true,
    inStock: true,
    stockQuantity: 140,
    date: Date.now(),
  },
  {
    name: "Sourdough Bread",
    price: 4.29,
    description:
      "Artisan sourdough loaf with a crisp crust and airy crumb, baked fresh daily.",
    images: [
      "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Bakery Items",
    subCategory: "Bread",
    unit: "loaf",
    sizes: ["600g"],
    nutritionInfo: {
      calories: 240,
      protein: "8g",
      carbs: "46g",
      fat: "2g",
    },
    origin: "Local bakery",
    shelfLife: "2-3 days",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 90,
    date: Date.now(),
  },
  {
    name: "Free-Range Brown Eggs",
    price: 3.59,
    description:
      "Dozen large free-range brown eggs with rich yolks and high protein.",
    images: [
      "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Breakfast",
    subCategory: "Eggs",
    unit: "dozen",
    sizes: ["12 eggs"],
    nutritionInfo: {
      calories: 155,
      protein: "13g",
      carbs: "1.1g",
      fat: "11g",
    },
    origin: "Free-range farms",
    shelfLife: "3 weeks chilled",
    isOrganic: true,
    bestseller: true,
    inStock: true,
    stockQuantity: 180,
    date: Date.now(),
  },
  {
    name: "Cold Brew Coffee Concentrate",
    price: 6.99,
    description:
      "Smooth, low-acid cold brew concentrate — just add milk or water and ice.",
    images: [
      "https://images.unsplash.com/photo-1510626176961-4b37d0b4e904?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Drinks",
    subCategory: "Coffee",
    unit: "bottle",
    sizes: ["500ml"],
    nutritionInfo: {
      calories: 5,
      protein: "0g",
      carbs: "1g",
      fat: "0g",
    },
    origin: "House brew",
    shelfLife: "14 days chilled",
    isOrganic: false,
    bestseller: false,
    inStock: true,
    stockQuantity: 110,
    date: Date.now(),
  },
  {
    name: "Skinless Chicken Breast",
    price: 7.49,
    description:
      "Lean, boneless, skinless chicken breast — trimmed and ready to cook.",
    images: [
      "https://images.unsplash.com/photo-1604908812715-5f020f57f23c?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Meat & Seafood",
    subCategory: "Poultry",
    unit: "kg",
    sizes: ["500g", "1kg"],
    nutritionInfo: {
      calories: 165,
      protein: "31g",
      carbs: "0g",
      fat: "3.6g",
    },
    origin: "Local farms",
    shelfLife: "2-3 days chilled",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 95,
    date: Date.now(),
  },
  // --- New Electronics sector ---
  {
    name: "Ultrabook Pro 14",
    price: 1199.99,
    description:
      "Lightweight 14-inch ultrabook with Intel i7, 16GB RAM, 512GB SSD, 2.8K display, Wi‑Fi 6E, backlit keyboard.",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Laptops",
    unit: "unit",
    sizes: ["i7/16GB/512GB", "i7/32GB/1TB"],
    sizePricing: {
      "i7/16GB/512GB": 1199.99,
      "i7/32GB/1TB": 1499.99,
    },
    sizeStock: {
      "i7/16GB/512GB": 20,
      "i7/32GB/1TB": 15,
    },
    brand: "TechPro",
    model: "UP14-7130",
    warranty: "2 Years Official Warranty",
    specs: {
      Processor: "Intel Core i7-1360P",
      RAM: "16GB LPDDR5",
      Storage: "512GB NVMe SSD",
      Display: '14" 2.8K (2880x1800) 90Hz',
      Graphics: "Intel Iris Xe",
      Weight: "1.25 kg",
      Ports: "2x Thunderbolt 4, HDMI 2.0, Audio combo",
    },
    bestseller: true,
    inStock: true,
    stockQuantity: 35,
    discount: 10,
    date: Date.now(),
  },
  {
    name: "Noise-Canceling Headphones X200",
    price: 299.99,
    description:
      "Wireless over-ear ANC headphones with 40h battery, LDAC, multipoint Bluetooth, and spatial audio.",
    images: [
      "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Headphones",
    unit: "unit",
    sizes: ["One Size"],
    brand: "SoundMax",
    model: "X200 ANC",
    warranty: "12 Months Official Warranty",
    specs: {
      Driver: "40mm dynamic",
      ANC: "Hybrid Active Noise Cancellation",
      Codec: "LDAC / AAC / SBC",
      Battery: "Up to 40h (ANC on)",
      Charge: "USB-C Fast Charge (10 min = 5h)",
      Weight: "265 g",
      Mic: "6-mic array with ENC",
    },
    bestseller: true,
    inStock: true,
    stockQuantity: 120,
    discount: 15,
    date: Date.now(),
  },
  {
    name: "Smart Home Hub Mini",
    price: 89.99,
    description:
      "Compact smart home hub with voice assistant, Matter, Thread border router, and Zigbee bridge built-in.",
    images: [
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Smart Home",
    unit: "unit",
    sizes: ["One Size"],
    brand: "HomeLink",
    model: "HL-MINI",
    warranty: "1 Year Official Warranty",
    specs: {
      Protocols: "Matter, Thread, Zigbee, Wi‑Fi",
      Voice: "Built-in voice assistant",
      Ports: "USB-C power",
      App: "HomeLink App (iOS/Android)",
      Automation: "Routines, schedules, remote control",
    },
    bestseller: false,
    inStock: true,
    stockQuantity: 200,
    discount: 5,
    date: Date.now(),
  },
  // --- New Fashion sector ---
  {
    name: "Men's TechStretch Hoodie",
    price: 79.99,
    description:
      "Moisture-wicking, 4-way stretch hoodie with hidden zip pocket and reflective trims.",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Men",
    unit: "piece",
    sizes: ["S", "M", "L", "XL"],
    bestseller: true,
    inStock: true,
    stockQuantity: 180,
    discount: 20,
    date: Date.now(),
  },
  {
    name: "Women's Minimalist Crossbody",
    price: 129.0,
    description:
      "Premium vegan-leather crossbody with magnetic flap, adjustable strap, and hidden phone slot.",
    images: [
      "https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Accessories",
    unit: "piece",
    sizes: ["One Size"],
    bestseller: true,
    inStock: true,
    stockQuantity: 95,
    discount: 0,
    date: Date.now(),
  },
  {
    name: "Everyday Runner Sneakers",
    price: 110.0,
    description:
      "Lightweight daily trainers with responsive foam, breathable mesh, and reflective accents.",
    images: [
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Shoes",
    unit: "pair",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
    bestseller: false,
    inStock: true,
    stockQuantity: 150,
    discount: 10,
    date: Date.now(),
  },
  // --- Additional Electronics ---
  {
    name: "Galaxy S24 Ultra Smartphone",
    price: 1299.99,
    description:
      "Premium flagship smartphone with 200MP camera, S Pen, 6.8-inch AMOLED display, Snapdragon 8 Gen 3, and 5000mAh battery.",
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Smartphones",
    unit: "unit",
    sizes: ["8GB+256GB", "12GB+512GB", "12GB+1TB"],
    sizePricing: {
      "8GB+256GB": 1199.99,
      "12GB+512GB": 1299.99,
      "12GB+1TB": 1499.99,
    },
    sizeStock: {
      "8GB+256GB": 25,
      "12GB+512GB": 30,
      "12GB+1TB": 10,
    },
    brand: "Samsung",
    model: "Galaxy S24 Ultra",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Snapdragon 8 Gen 3 for Galaxy",
      Display: '6.8" QHD+ Dynamic AMOLED 2X 120Hz',
      Camera: "200MP + 12MP + 10MP + 10MP, 12MP front",
      Battery: "5000mAh, 45W fast charge",
      Connectivity: "5G, Wi‑Fi 7, BT 5.3, NFC",
      Extras: "S Pen, IP68",
    },
    bestseller: true,
    inStock: true,
    stockQuantity: 65,
    discount: 5,
    date: Date.now(),
  },
  {
    name: "4K Smart TV 55-inch",
    price: 599.99,
    description:
      "55-inch 4K UHD Smart TV with HDR10+, Dolby Vision, built-in streaming apps, and voice control.",
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Televisions",
    unit: "unit",
    sizes: ["55-inch"],
    brand: "ViewPlus",
    model: "VP-55UHD",
    warranty: "3 Years Panel Warranty",
    specs: {
      Panel: "VA, 4K UHD, 60Hz",
      HDR: "HDR10+ / Dolby Vision",
      OS: "Android TV 12",
      Audio: "20W speakers, Dolby Audio",
      Ports: "3x HDMI 2.1, 2x USB, eARC",
      Connectivity: "Wi‑Fi, Bluetooth",
    },
    bestseller: true,
    inStock: true,
    stockQuantity: 30,
    discount: 12,
    date: Date.now(),
  },
  {
    name: "Fitness Smartwatch Pro",
    price: 249.99,
    description:
      "Advanced fitness tracker with dual-band GPS, SpO2, HRV, sleep tracking, and 7-day battery life.",
    images: [
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Wearables",
    unit: "unit",
    sizes: ["40mm", "44mm"],
    brand: "FitCore",
    model: "FW-Pro",
    warranty: "1 Year Official Warranty",
    specs: {
      Display: '1.43" AMOLED, AOD',
      GPS: "Dual-band L1+L5",
      Sensors: "HR, SpO2, HRV, Compass",
      Battery: "Up to 7 days typical",
      Water: "5ATM",
      Connectivity: "BT 5.3",
    },
    bestseller: false,
    inStock: true,
    stockQuantity: 160,
    discount: 8,
    date: Date.now(),
  },
  // --- Additional Fashion ---
  {
    name: "Women's Denim Jacket",
    price: 89.99,
    description:
      "Classic blue denim jacket with vintage wash, button closure, and chest pockets.",
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Women",
    unit: "piece",
    sizes: ["S", "M", "L", "XL"],
    bestseller: true,
    inStock: true,
    stockQuantity: 110,
    discount: 15,
    date: Date.now(),
  },
  {
    name: "Men's Slim Fit Chinos",
    price: 59.99,
    description:
      "Modern slim-fit chino pants in stretch cotton twill with flat front and tapered leg.",
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Men",
    unit: "piece",
    sizes: ["30", "32", "34", "36", "38"],
    bestseller: false,
    inStock: true,
    stockQuantity: 145,
    discount: 10,
    date: Date.now(),
  },
  {
    name: "Leather Ankle Boots",
    price: 139.99,
    description:
      "Premium leather ankle boots with side zip, cushioned insole, and durable rubber sole.",
    images: [
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Shoes",
    unit: "pair",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10"],
    bestseller: true,
    inStock: true,
    stockQuantity: 85,
    discount: 0,
    date: Date.now(),
  },
  {
    name: "Yoga Leggings High-Waist",
    price: 49.99,
    description:
      "High-waisted yoga leggings with moisture-wicking fabric, hidden pocket, and 4-way stretch.",
    images: [
      "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Activewear",
    unit: "piece",
    sizes: ["XS", "S", "M", "L", "XL"],
    bestseller: false,
    inStock: true,
    stockQuantity: 200,
    discount: 20,
    date: Date.now(),
  },
  {
    name: "Atlantic Salmon Fillet",
    price: 14.99,
    description:
      "Fresh Atlantic salmon fillet, rich in omega-3, skin-on for crisp sear.",
    images: [
      "https://images.unsplash.com/photo-1604908177545-02f6687b4446?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Meat & Seafood",
    subCategory: "Seafood",
    unit: "kg",
    sizes: ["250g", "500g", "1kg"],
    nutritionInfo: {
      calories: 208,
      protein: "20g",
      carbs: "0g",
      fat: "13g",
    },
    origin: "Norway",
    shelfLife: "2 days chilled",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 60,
    date: Date.now(),
  },
  {
    name: "Aged Basmati Rice",
    price: 11.49,
    description:
      "2-year aged long-grain basmati rice with aromatic flavor and extra length.",
    images: [
      "https://images.unsplash.com/photo-1477505982272-ead89926a577?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Grains & Cereals",
    subCategory: "Rice",
    unit: "kg",
    sizes: ["1kg", "5kg"],
    nutritionInfo: {
      calories: 365,
      protein: "7.1g",
      carbs: "80g",
      fat: "0.7g",
    },
    origin: "India",
    shelfLife: "12 months",
    isOrganic: false,
    bestseller: false,
    inStock: true,
    stockQuantity: 130,
    date: Date.now(),
  },
  {
    name: "Dry Roasted Almonds",
    price: 8.49,
    description:
      "Crunchy dry roasted almonds without added oil; great snack or topping.",
    images: [
      "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Snacks",
    subCategory: "Nuts",
    unit: "pack",
    sizes: ["200g", "500g"],
    nutritionInfo: {
      calories: 579,
      protein: "21g",
      carbs: "22g",
      fat: "50g",
    },
    origin: "California",
    shelfLife: "6 months",
    isOrganic: true,
    bestseller: false,
    inStock: true,
    stockQuantity: 160,
    date: Date.now(),
  },
  {
    name: "Honey Almond Granola",
    price: 6.79,
    description:
      "Crunchy baked granola with rolled oats, honey, and roasted almonds.",
    images: [
      "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Breakfast",
    subCategory: "Cereal",
    unit: "pack",
    sizes: ["350g", "700g"],
    nutritionInfo: {
      calories: 430,
      protein: "10g",
      carbs: "62g",
      fat: "14g",
    },
    origin: "USA",
    shelfLife: "6 months",
    isOrganic: false,
    bestseller: false,
    inStock: true,
    stockQuantity: 140,
    date: Date.now(),
  },
  {
    name: "Hass Avocado",
    price: 1.99,
    description:
      "Creamy Hass avocado with rich flavor — perfect for toast and salads.",
    images: [
      "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Fresh Fruits",
    subCategory: "Avocado",
    unit: "piece",
    sizes: ["Single", "Pack of 4"],
    nutritionInfo: {
      calories: 160,
      protein: "2g",
      carbs: "9g",
      fat: "15g",
    },
    origin: "Mexico",
    shelfLife: "3-5 days",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 170,
    date: Date.now(),
  },
  {
    name: "Smartphone X200",
    price: 32000,
    description: "6.5-inch FHD+ display, 6GB RAM, 128GB storage, dual SIM.",
    images: [
      "https://picsum.photos/seed/electronics1a/800/800",
      "https://picsum.photos/seed/electronics1b/800/800",
      "https://picsum.photos/seed/electronics1c/800/800",
    ],
    category: "Electronics",
    subCategory: "Smartphones",
    sizes: ["128GB", "256GB"],
    sizeStock: { "128GB": 25, "256GB": 10 },
    brand: "TechNova",
    model: "X200",
    warranty: "1 year warranty",
    specs: {
      Display: "6.5-inch FHD+",
      Processor: "Octa-core 2.2GHz",
      RAM: "6GB",
      Storage: "128GB",
      Battery: "5000mAh",
      OS: "Android 14",
    },
    tags: ["smartphone", "android", "dual sim"],
    weight: "180g",
    dimensions: {
      width: "75mm",
      height: "160mm",
      depth: "8.5mm",
    },
    origin: "China",
    discount: 5,
    bestseller: true,
    isOrganic: false,
    inStock: true,
    stockQuantity: 35,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Smartphone X210",
    price: 36000,
    description: "6.7-inch AMOLED display, 8GB RAM, 256GB storage, 5G support.",
    images: [
      "https://picsum.photos/seed/electronics2a/800/800",
      "https://picsum.photos/seed/electronics2b/800/800",
      "https://picsum.photos/seed/electronics2c/800/800",
    ],
    category: "Electronics",
    subCategory: "Smartphones",
    sizes: ["128GB", "256GB"],
    sizeStock: { "128GB": 15, "256GB": 12 },
    brand: "TechNova",
    model: "X210",
    warranty: "1 year warranty",
    specs: {
      Display: "6.7-inch AMOLED",
      Processor: "Octa-core 2.6GHz",
      RAM: "8GB",
      Storage: "256GB",
      Battery: "5200mAh",
      OS: "Android 14",
    },
    tags: ["smartphone", "5g", "android"],
    weight: "185g",
    dimensions: {
      width: "76mm",
      height: "162mm",
      depth: "8.3mm",
    },
    origin: "China",
    discount: 7,
    bestseller: true,
    isOrganic: false,
    inStock: true,
    stockQuantity: 27,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Wireless Earbuds AirLite",
    price: 3500,
    description:
      "True wireless earbuds with noise isolation and 24-hour playtime.",
    images: [
      "https://picsum.photos/seed/electronics3a/800/800",
      "https://picsum.photos/seed/electronics3b/800/800",
    ],
    category: "Electronics",
    subCategory: "Audio",
    sizes: ["Standard"],
    sizeStock: { Standard: 40 },
    brand: "SoundFlow",
    model: "AirLite",
    warranty: "6 months warranty",
    specs: {
      Connectivity: "Bluetooth 5.3",
      Playtime: "24 hours with case",
      Charging: "USB-C fast charging",
      WaterRating: "IPX4",
    },
    tags: ["earbuds", "wireless", "audio"],
    weight: "45g",
    dimensions: {
      width: "60mm",
      height: "45mm",
      depth: "25mm",
    },
    origin: "Vietnam",
    discount: 12,
    bestseller: true,
    isOrganic: false,
    inStock: true,
    stockQuantity: 40,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Noise Cancelling Headphones Pro",
    price: 7800,
    description: "Over-ear wireless headphones with active noise cancellation.",
    images: [
      "https://picsum.photos/seed/electronics4a/800/800",
      "https://picsum.photos/seed/electronics4b/800/800",
      "https://picsum.photos/seed/electronics4c/800/800",
    ],
    category: "Electronics",
    subCategory: "Audio",
    sizes: ["Standard"],
    sizeStock: { Standard: 18 },
    brand: "SoundFlow",
    model: "NC Pro",
    warranty: "1 year warranty",
    specs: {
      Connectivity: "Bluetooth 5.2",
      Playtime: "30 hours",
      Features: "ANC, Transparency mode",
      Charging: "USB-C",
    },
    tags: ["headphones", "noise cancelling", "wireless"],
    weight: "240g",
    dimensions: {
      width: "170mm",
      height: "190mm",
      depth: "75mm",
    },
    origin: "Malaysia",
    discount: 10,
    bestseller: false,
    isOrganic: false,
    inStock: true,
    stockQuantity: 18,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "4K Smart LED TV 43-inch",
    price: 42000,
    description: "43-inch 4K UHD smart TV with HDR and built-in apps.",
    images: [
      "https://picsum.photos/seed/electronics5a/800/800",
      "https://picsum.photos/seed/electronics5b/800/800",
    ],
    category: "Electronics",
    subCategory: "Television",
    sizes: ["43 inch"],
    sizeStock: { "43 inch": 12 },
    brand: "ViewMax",
    model: "VM43UHD",
    warranty: "2 years warranty",
    specs: {
      Resolution: "4K UHD",
      Panel: "LED",
      SmartOS: "Android TV",
      Ports: "3x HDMI, 2x USB",
    },
    tags: ["tv", "4k", "smart tv"],
    weight: "7.5kg",
    dimensions: {
      width: "960mm",
      height: "560mm",
      depth: "80mm",
    },
    origin: "India",
    discount: 9,
    bestseller: true,
    isOrganic: false,
    inStock: true,
    stockQuantity: 12,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Bluetooth Speaker MiniBoom",
    price: 1800,
    description:
      "Portable Bluetooth speaker with deep bass and 10-hour battery.",
    images: [
      "https://picsum.photos/seed/electronics6a/800/800",
      "https://picsum.photos/seed/electronics6b/800/800",
      "https://picsum.photos/seed/electronics6c/800/800",
    ],
    category: "Electronics",
    subCategory: "Audio",
    sizes: ["Standard"],
    sizeStock: { Standard: 30 },
    brand: "BeatBox",
    model: "MiniBoom",
    warranty: "6 months warranty",
    specs: {
      Connectivity: "Bluetooth 5.0",
      Playtime: "10 hours",
      WaterRating: "IPX5",
      Features: "Hands-free calling",
    },
    tags: ["speaker", "bluetooth", "portable"],
    weight: "350g",
    dimensions: {
      width: "70mm",
      height: "90mm",
      depth: "70mm",
    },
    origin: "China",
    discount: 15,
    bestseller: true,
    isOrganic: false,
    inStock: true,
    stockQuantity: 30,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Gaming Mouse GX500",
    price: 1200,
    description: "Ergonomic gaming mouse with RGB and 7200 DPI sensor.",
    images: [
      "https://picsum.photos/seed/electronics7a/800/800",
      "https://picsum.photos/seed/electronics7b/800/800",
    ],
    category: "Electronics",
    subCategory: "Accessories",
    sizes: ["Standard"],
    sizeStock: { Standard: 45 },
    brand: "ProClick",
    model: "GX500",
    warranty: "1 year warranty",
    specs: {
      DPI: "800–7200",
      Buttons: "7 programmable",
      Connection: "USB wired",
      Lighting: "RGB",
    },
    tags: ["mouse", "gaming", "accessory"],
    weight: "110g",
    dimensions: {
      width: "67mm",
      height: "40mm",
      depth: "125mm",
    },
    origin: "China",
    discount: 8,
    bestseller: true,
    isOrganic: false,
    inStock: true,
    stockQuantity: 45,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Mechanical Keyboard MX Blue",
    price: 3200,
    description:
      "Full-size mechanical keyboard with blue switches and backlight.",
    images: [
      "https://picsum.photos/seed/electronics8a/800/800",
      "https://picsum.photos/seed/electronics8b/800/800",
      "https://picsum.photos/seed/electronics8c/800/800",
    ],
    category: "Electronics",
    subCategory: "Accessories",
    sizes: ["Standard"],
    sizeStock: { Standard: 22 },
    brand: "KeyWave",
    model: "MX Blue",
    warranty: "1 year warranty",
    specs: {
      Layout: "104 keys",
      Switch: "Blue clicky",
      Backlight: "RGB",
      Connection: "USB wired",
    },
    tags: ["keyboard", "mechanical", "gaming"],
    weight: "850g",
    dimensions: {
      width: "440mm",
      height: "35mm",
      depth: "135mm",
    },
    origin: "Taiwan",
    discount: 10,
    bestseller: false,
    isOrganic: false,
    inStock: true,
    stockQuantity: 22,
    unit: "pcs",
    date: 1705276800000,
  },

  /* ---- FOOD / GROCERY (about 20 items) ---- */

  {
    name: "Organic Brown Rice 1kg",
    price: 160,
    description: "Premium long-grain organic brown rice, rich in fiber.",
    images: [
      "https://picsum.photos/seed/food1a/800/800",
      "https://picsum.photos/seed/food1b/800/800",
    ],
    category: "Grocery",
    subCategory: "Rice & Grains",
    unit: "kg",
    sizes: ["1kg", "2kg", "5kg"],
    sizeStock: { "1kg": 40, "2kg": 25, "5kg": 10 },
    brand: "GreenHarvest",
    tags: ["organic", "rice", "whole grain"],
    isOrganic: true,
    discount: 5,
    bestseller: true,
    inStock: true,
    stockQuantity: 75,
    nutritionInfo: {
      calories: 216,
      protein: "5g",
      carbs: "45g",
      fat: "1.8g",
    },
    origin: "Bangladesh",
    shelfLife: "12 months",
    weight: "1kg",
    dimensions: {
      width: "80mm",
      height: "260mm",
      depth: "60mm",
    },
    date: 1705276800000,
  },
  {
    name: "Premium Basmati Rice 1kg",
    price: 190,
    description:
      "Aromatic long-grain basmati rice ideal for biryani and pulao.",
    images: [
      "https://picsum.photos/seed/food2a/800/800",
      "https://picsum.photos/seed/food2b/800/800",
    ],
    category: "Grocery",
    subCategory: "Rice & Grains",
    unit: "kg",
    sizes: ["1kg", "2kg"],
    sizeStock: { "1kg": 35, "2kg": 20 },
    brand: "RoyalGrain",
    tags: ["basmati", "rice", "aromatic"],
    isOrganic: false,
    discount: 0,
    bestseller: true,
    inStock: true,
    stockQuantity: 55,
    nutritionInfo: {
      calories: 205,
      protein: "4.2g",
      carbs: "44g",
      fat: "0.4g",
    },
    origin: "India",
    shelfLife: "18 months",
    weight: "1kg",
    dimensions: {
      width: "80mm",
      height: "260mm",
      depth: "60mm",
    },
    date: 1705276800000,
  },
  {
    name: "Organic Lentils 500g",
    price: 110,
    description: "Protein-rich organic red lentils for everyday cooking.",
    images: [
      "https://picsum.photos/seed/food3a/800/800",
      "https://picsum.photos/seed/food3b/800/800",
    ],
    category: "Grocery",
    subCategory: "Pulses",
    unit: "kg",
    sizes: ["500g", "1kg"],
    sizeStock: { "500g": 60, "1kg": 30 },
    brand: "GreenHarvest",
    tags: ["organic", "lentils", "protein"],
    isOrganic: true,
    discount: 7,
    bestseller: true,
    inStock: true,
    stockQuantity: 90,
    nutritionInfo: {
      calories: 230,
      protein: "18g",
      carbs: "40g",
      fat: "0.8g",
    },
    origin: "Bangladesh",
    shelfLife: "10 months",
    weight: "500g",
    dimensions: {
      width: "70mm",
      height: "220mm",
      depth: "50mm",
    },
    date: 1705276800000,
  },
  {
    name: "Premium Tea Bags 100pcs",
    price: 220,
    description: "Strong and flavorful black tea bags in a value pack.",
    images: [
      "https://picsum.photos/seed/food4a/800/800",
      "https://picsum.photos/seed/food4b/800/800",
      "https://picsum.photos/seed/food4c/800/800",
    ],
    category: "Grocery",
    subCategory: "Beverages",
    unit: "pcs",
    sizes: ["Box"],
    sizeStock: { Box: 45 },
    brand: "ChaiGold",
    tags: ["tea", "beverage", "black tea"],
    isOrganic: false,
    discount: 10,
    bestseller: true,
    inStock: true,
    stockQuantity: 45,
    nutritionInfo: {
      calories: 2,
      protein: "0g",
      carbs: "0g",
      fat: "0g",
    },
    origin: "Sri Lanka",
    shelfLife: "24 months",
    weight: "200g",
    dimensions: {
      width: "120mm",
      height: "80mm",
      depth: "70mm",
    },
    date: 1705276800000,
  },
  {
    name: "Instant Coffee Classic 200g",
    price: 320,
    description: "Rich and smooth instant coffee, perfect for quick brews.",
    images: [
      "https://picsum.photos/seed/food5a/800/800",
      "https://picsum.photos/seed/food5b/800/800",
    ],
    category: "Grocery",
    subCategory: "Beverages",
    unit: "pcs",
    sizes: ["200g jar"],
    sizeStock: { "200g jar": 35 },
    brand: "CafePrime",
    tags: ["coffee", "instant", "beverage"],
    isOrganic: false,
    discount: 12,
    bestseller: true,
    inStock: true,
    stockQuantity: 35,
    nutritionInfo: {
      calories: 5,
      protein: "0.2g",
      carbs: "1g",
      fat: "0g",
    },
    origin: "Vietnam",
    shelfLife: "18 months",
    weight: "200g",
    dimensions: {
      width: "70mm",
      height: "140mm",
      depth: "70mm",
    },
    date: 1705276800000,
  },
  {
    name: "Organic Honey 500g",
    price: 350,
    description: "Raw, unfiltered organic honey from wildflowers.",
    images: [
      "https://picsum.photos/seed/food6a/800/800",
      "https://picsum.photos/seed/food6b/800/800",
    ],
    category: "Grocery",
    subCategory: "Spreads",
    unit: "kg",
    sizes: ["250g", "500g"],
    sizeStock: { "250g": 40, "500g": 25 },
    brand: "BeePure",
    tags: ["honey", "organic", "natural"],
    isOrganic: true,
    discount: 5,
    bestseller: true,
    inStock: true,
    stockQuantity: 65,
    nutritionInfo: {
      calories: 304,
      protein: "0.3g",
      carbs: "82g",
      fat: "0g",
    },
    origin: "Bangladesh",
    shelfLife: "24 months",
    weight: "500g",
    dimensions: {
      width: "70mm",
      height: "150mm",
      depth: "70mm",
    },
    date: 1705276800000,
  },
  {
    name: "Peanut Butter Creamy 340g",
    price: 280,
    description: "Smooth and creamy peanut butter with no added preservatives.",
    images: [
      "https://picsum.photos/seed/food7a/800/800",
      "https://picsum.photos/seed/food7b/800/800",
    ],
    category: "Grocery",
    subCategory: "Spreads",
    unit: "pcs",
    sizes: ["340g jar"],
    sizeStock: { "340g jar": 30 },
    brand: "NutriSpread",
    tags: ["peanut butter", "spread", "protein"],
    isOrganic: false,
    discount: 8,
    bestseller: false,
    inStock: true,
    stockQuantity: 30,
    nutritionInfo: {
      calories: 588,
      protein: "25g",
      carbs: "20g",
      fat: "50g",
    },
    origin: "USA",
    shelfLife: "12 months",
    weight: "340g",
    dimensions: {
      width: "80mm",
      height: "110mm",
      depth: "80mm",
    },
    date: 1705276800000,
  },
  {
    name: "Corn Flakes Cereal 500g",
    price: 260,
    description:
      "Crispy golden corn flakes fortified with vitamins and minerals.",
    images: [
      "https://picsum.photos/seed/food8a/800/800",
      "https://picsum.photos/seed/food8b/800/800",
    ],
    category: "Grocery",
    subCategory: "Breakfast",
    unit: "pcs",
    sizes: ["500g box"],
    sizeStock: { "500g box": 28 },
    brand: "MorningCrunch",
    tags: ["cereal", "breakfast", "corn flakes"],
    isOrganic: false,
    discount: 6,
    bestseller: true,
    inStock: true,
    stockQuantity: 28,
    nutritionInfo: {
      calories: 375,
      protein: "7g",
      carbs: "84g",
      fat: "1g",
    },
    origin: "India",
    shelfLife: "10 months",
    weight: "500g",
    dimensions: {
      width: "150mm",
      height: "270mm",
      depth: "60mm",
    },
    date: 1705276800000,
  },
  {
    name: "Granola Mix 400g",
    price: 340,
    description: "Granola with oats, nuts, seeds, and dried fruits.",
    images: [
      "https://picsum.photos/seed/food9a/800/800",
      "https://picsum.photos/seed/food9b/800/800",
    ],
    category: "Grocery",
    subCategory: "Breakfast",
    unit: "pcs",
    sizes: ["400g pouch"],
    sizeStock: { "400g pouch": 22 },
    brand: "HealthyBite",
    tags: ["granola", "oats", "breakfast"],
    isOrganic: true,
    discount: 10,
    bestseller: false,
    inStock: true,
    stockQuantity: 22,
    nutritionInfo: {
      calories: 420,
      protein: "10g",
      carbs: "60g",
      fat: "15g",
    },
    origin: "Bangladesh",
    shelfLife: "8 months",
    weight: "400g",
    dimensions: {
      width: "140mm",
      height: "240mm",
      depth: "60mm",
    },
    date: 1705276800000,
  },
  {
    name: "Dark Chocolate 70% 100g",
    price: 150,
    description: "Rich dark chocolate with 70% cocoa content.",
    images: [
      "https://picsum.photos/seed/food10a/800/800",
      "https://picsum.photos/seed/food10b/800/800",
    ],
    category: "Grocery",
    subCategory: "Snacks",
    unit: "pcs",
    sizes: ["100g bar"],
    sizeStock: { "100g bar": 40 },
    brand: "ChocoFine",
    tags: ["chocolate", "dark", "snack"],
    isOrganic: false,
    discount: 5,
    bestseller: true,
    inStock: true,
    stockQuantity: 40,
    nutritionInfo: {
      calories: 600,
      protein: "7g",
      carbs: "46g",
      fat: "43g",
    },
    origin: "Belgium",
    shelfLife: "18 months",
    weight: "100g",
    dimensions: {
      width: "70mm",
      height: "160mm",
      depth: "10mm",
    },
    date: 1705276800000,
  },
  {
    name: "Potato Chips Salted 150g",
    price: 90,
    description: "Crispy salted potato chips perfect for snacking.",
    images: [
      "https://picsum.photos/seed/food11a/800/800",
      "https://picsum.photos/seed/food11b/800/800",
    ],
    category: "Grocery",
    subCategory: "Snacks",
    unit: "pcs",
    sizes: ["150g pack"],
    sizeStock: { "150g pack": 60 },
    brand: "CrispyBite",
    tags: ["chips", "snacks", "salted"],
    isOrganic: false,
    discount: 0,
    bestseller: true,
    inStock: true,
    stockQuantity: 60,
    nutritionInfo: {
      calories: 540,
      protein: "6g",
      carbs: "52g",
      fat: "34g",
    },
    origin: "Bangladesh",
    shelfLife: "6 months",
    weight: "150g",
    dimensions: {
      width: "160mm",
      height: "260mm",
      depth: "70mm",
    },
    date: 1705276800000,
  },
  {
    name: "Tomato Ketchup 750g",
    price: 130,
    description: "Thick and tangy tomato ketchup made from ripe tomatoes.",
    images: [
      "https://picsum.photos/seed/food12a/800/800",
      "https://picsum.photos/seed/food12b/800/800",
    ],
    category: "Grocery",
    subCategory: "Sauces",
    unit: "pcs",
    sizes: ["750g bottle"],
    sizeStock: { "750g bottle": 32 },
    brand: "SaucyFresh",
    tags: ["ketchup", "sauce", "condiment"],
    isOrganic: false,
    discount: 6,
    bestseller: false,
    inStock: true,
    stockQuantity: 32,
    nutritionInfo: {
      calories: 112,
      protein: "1.3g",
      carbs: "26g",
      fat: "0.2g",
    },
    origin: "India",
    shelfLife: "12 months",
    weight: "750g",
    dimensions: {
      width: "70mm",
      height: "250mm",
      depth: "70mm",
    },
    date: 1705276800000,
  },
  {
    name: "Pasta Penne 500g",
    price: 140,
    description: "Durum wheat pasta penne, perfect for quick meals.",
    images: [
      "https://picsum.photos/seed/food13a/800/800",
      "https://picsum.photos/seed/food13b/800/800",
    ],
    category: "Grocery",
    subCategory: "Pasta",
    unit: "pcs",
    sizes: ["500g pack"],
    sizeStock: { "500g pack": 38 },
    brand: "PastaRoma",
    tags: ["pasta", "penne", "italian"],
    isOrganic: false,
    discount: 4,
    bestseller: false,
    inStock: true,
    stockQuantity: 38,
    nutritionInfo: {
      calories: 350,
      protein: "12g",
      carbs: "72g",
      fat: "1.5g",
    },
    origin: "Italy",
    shelfLife: "24 months",
    weight: "500g",
    dimensions: {
      width: "130mm",
      height: "230mm",
      depth: "50mm",
    },
    date: 1705276800000,
  },
  {
    name: "Olive Oil Extra Virgin 1L",
    price: 780,
    description: "Cold-pressed extra virgin olive oil for cooking and salads.",
    images: [
      "https://picsum.photos/seed/food14a/800/800",
      "https://picsum.photos/seed/food14b/800/800",
    ],
    category: "Grocery",
    subCategory: "Oils",
    unit: "pcs",
    sizes: ["1L bottle"],
    sizeStock: { "1L bottle": 18 },
    brand: "Mediterraneo",
    tags: ["olive oil", "extra virgin", "cooking"],
    isOrganic: true,
    discount: 10,
    bestseller: true,
    inStock: true,
    stockQuantity: 18,
    nutritionInfo: {
      calories: 884,
      protein: "0g",
      carbs: "0g",
      fat: "100g",
    },
    origin: "Spain",
    shelfLife: "24 months",
    weight: "1L",
    dimensions: {
      width: "80mm",
      height: "300mm",
      depth: "80mm",
    },
    date: 1705276800000,
  },
  {
    name: "Organic Tomatoes 1kg",
    price: 150,
    description: "Fresh, pesticide-free tomatoes from local farms.",
    images: [
      "https://picsum.photos/seed/food15a/800/800",
      "https://picsum.photos/seed/food15b/800/800",
      "https://picsum.photos/seed/food15c/800/800",
    ],
    category: "Grocery",
    subCategory: "Vegetables",
    unit: "kg",
    sizes: ["1kg", "2kg"],
    sizeStock: { "1kg": 50, "2kg": 25 },
    brand: "FarmFresh",
    tags: ["organic", "fresh", "vegetables"],
    isOrganic: true,
    discount: 10,
    bestseller: true,
    inStock: true,
    stockQuantity: 75,
    nutritionInfo: {
      calories: 18,
      protein: "0.9g",
      carbs: "3.9g",
      fat: "0.2g",
    },
    origin: "Bangladesh",
    shelfLife: "3-5 days",
    weight: "1kg",
    dimensions: {
      width: "140mm",
      height: "90mm",
      depth: "90mm",
    },
    date: 1705276800000,
  },

  /* ---- CLOTHING (around 22 items to reach total 50) ---- */

  {
    name: "Men's Casual T-Shirt",
    price: 550,
    description: "Soft cotton round-neck t-shirt for everyday wear.",
    images: [
      "https://picsum.photos/seed/clothing1a/800/800",
      "https://picsum.photos/seed/clothing1b/800/800",
    ],
    category: "Fashion",
    subCategory: "Men",
    sizes: ["S", "M", "L", "XL"],
    sizeStock: { S: 10, M: 20, L: 18, XL: 8 },
    brand: "UrbanWear",
    tags: ["tshirt", "men", "casual"],
    weight: "180g",
    dimensions: {
      width: "300mm",
      height: "10mm",
      depth: "250mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: true,
    discount: 5,
    inStock: true,
    stockQuantity: 56,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Men's Polo Shirt",
    price: 750,
    description: "Classic pique polo shirt with buttoned collar.",
    images: [
      "https://picsum.photos/seed/clothing2a/800/800",
      "https://picsum.photos/seed/clothing2b/800/800",
    ],
    category: "Fashion",
    subCategory: "Men",
    sizes: ["S", "M", "L", "XL"],
    sizeStock: { S: 8, M: 16, L: 14, XL: 6 },
    brand: "UrbanWear",
    tags: ["polo", "men", "casual"],
    weight: "220g",
    dimensions: {
      width: "300mm",
      height: "10mm",
      depth: "250mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: false,
    discount: 10,
    inStock: true,
    stockQuantity: 44,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Men's Formal Shirt",
    price: 1250,
    description: "Slim-fit formal shirt suitable for office and events.",
    images: [
      "https://picsum.photos/seed/clothing3a/800/800",
      "https://picsum.photos/seed/clothing3b/800/800",
    ],
    category: "Fashion",
    subCategory: "Men",
    sizes: ["S", "M", "L", "XL"],
    sizeStock: { S: 6, M: 14, L: 12, XL: 5 },
    brand: "ClassicLine",
    tags: ["shirt", "formal", "men"],
    weight: "260g",
    dimensions: {
      width: "320mm",
      height: "15mm",
      depth: "260mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: true,
    discount: 12,
    inStock: true,
    stockQuantity: 37,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Men's Denim Jeans",
    price: 1450,
    description: "Straight-fit denim jeans with medium wash.",
    images: [
      "https://picsum.photos/seed/clothing4a/800/800",
      "https://picsum.photos/seed/clothing4b/800/800",
    ],
    category: "Fashion",
    subCategory: "Men",
    sizes: ["30", "32", "34", "36"],
    sizeStock: { 30: 8, 32: 15, 34: 12, 36: 7 },
    brand: "BlueStone",
    tags: ["jeans", "denim", "men"],
    weight: "650g",
    dimensions: {
      width: "340mm",
      height: "40mm",
      depth: "260mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: true,
    discount: 8,
    inStock: true,
    stockQuantity: 42,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Women's Casual Top",
    price: 680,
    description: "Lightweight printed top for daily wear.",
    images: [
      "https://picsum.photos/seed/clothing5a/800/800",
      "https://picsum.photos/seed/clothing5b/800/800",
    ],
    category: "Fashion",
    subCategory: "Women",
    sizes: ["S", "M", "L"],
    sizeStock: { S: 10, M: 16, L: 12 },
    brand: "StyleVista",
    tags: ["top", "women", "casual"],
    weight: "200g",
    dimensions: {
      width: "290mm",
      height: "10mm",
      depth: "240mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: true,
    discount: 5,
    inStock: true,
    stockQuantity: 38,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Women's Kurti",
    price: 1150,
    description: "Embroidered cotton kurti with three-quarter sleeves.",
    images: [
      "https://picsum.photos/seed/clothing6a/800/800",
      "https://picsum.photos/seed/clothing6b/800/800",
    ],
    category: "Fashion",
    subCategory: "Women",
    sizes: ["S", "M", "L", "XL"],
    sizeStock: { S: 6, M: 12, L: 10, XL: 5 },
    brand: "EthnicCharm",
    tags: ["kurti", "women", "ethnic"],
    weight: "260g",
    dimensions: {
      width: "310mm",
      height: "15mm",
      depth: "250mm",
    },
    origin: "India",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: false,
    discount: 10,
    inStock: true,
    stockQuantity: 33,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Women's Palazzo Pants",
    price: 900,
    description: "Flowy rayon palazzo pants with elastic waistband.",
    images: [
      "https://picsum.photos/seed/clothing7a/800/800",
      "https://picsum.photos/seed/clothing7b/800/800",
    ],
    category: "Fashion",
    subCategory: "Women",
    sizes: ["S", "M", "L"],
    sizeStock: { S: 8, M: 14, L: 10 },
    brand: "StyleVista",
    tags: ["palazzo", "women", "bottom"],
    weight: "240g",
    dimensions: {
      width: "320mm",
      height: "25mm",
      depth: "260mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: false,
    discount: 7,
    inStock: true,
    stockQuantity: 32,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Women's Maxi Dress",
    price: 1650,
    description: "Floral printed maxi dress with adjustable straps.",
    images: [
      "https://picsum.photos/seed/clothing8a/800/800",
      "https://picsum.photos/seed/clothing8b/800/800",
    ],
    category: "Fashion",
    subCategory: "Women",
    sizes: ["S", "M", "L"],
    sizeStock: { S: 5, M: 10, L: 8 },
    brand: "StyleVista",
    tags: ["dress", "women", "maxi"],
    weight: "280g",
    dimensions: {
      width: "320mm",
      height: "20mm",
      depth: "260mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: true,
    discount: 12,
    inStock: true,
    stockQuantity: 23,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Kids' T-Shirt",
    price: 420,
    description: "Colorful printed t-shirt for kids.",
    images: [
      "https://picsum.photos/seed/clothing9a/800/800",
      "https://picsum.photos/seed/clothing9b/800/800",
    ],
    category: "Fashion",
    subCategory: "Kids",
    sizes: ["2-4Y", "4-6Y", "6-8Y"],
    sizeStock: { "2-4Y": 10, "4-6Y": 12, "6-8Y": 9 },
    brand: "TinyTrends",
    tags: ["kids", "tshirt", "casual"],
    weight: "140g",
    dimensions: {
      width: "260mm",
      height: "8mm",
      depth: "220mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: true,
    discount: 5,
    inStock: true,
    stockQuantity: 31,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Kids' Denim Shorts",
    price: 600,
    description: "Comfortable denim shorts for kids' everyday activities.",
    images: [
      "https://picsum.photos/seed/clothing10a/800/800",
      "https://picsum.photos/seed/clothing10b/800/800",
    ],
    category: "Fashion",
    subCategory: "Kids",
    sizes: ["2-4Y", "4-6Y", "6-8Y"],
    sizeStock: { "2-4Y": 8, "4-6Y": 10, "6-8Y": 8 },
    brand: "TinyTrends",
    tags: ["kids", "shorts", "denim"],
    weight: "200g",
    dimensions: {
      width: "260mm",
      height: "20mm",
      depth: "220mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: false,
    discount: 8,
    inStock: true,
    stockQuantity: 26,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Unisex Hoodie",
    price: 1450,
    description:
      "Fleece-lined hoodie with adjustable drawstrings and kangaroo pocket.",
    images: [
      "https://picsum.photos/seed/clothing11a/800/800",
      "https://picsum.photos/seed/clothing11b/800/800",
    ],
    category: "Fashion",
    subCategory: "Unisex",
    sizes: ["S", "M", "L", "XL"],
    sizeStock: { S: 6, M: 12, L: 12, XL: 6 },
    brand: "CozyGear",
    tags: ["hoodie", "unisex", "winter"],
    weight: "700g",
    dimensions: {
      width: "340mm",
      height: "40mm",
      depth: "280mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: true,
    discount: 10,
    inStock: true,
    stockQuantity: 36,
    unit: "pcs",
    date: 1705276800000,
  },
  {
    name: "Unisex Sweatpants",
    price: 1150,
    description: "Comfort fit sweatpants with elastic waist and cuffs.",
    images: [
      "https://picsum.photos/seed/clothing12a/800/800",
      "https://picsum.photos/seed/clothing12b/800/800",
    ],
    category: "Fashion",
    subCategory: "Unisex",
    sizes: ["S", "M", "L", "XL"],
    sizeStock: { S: 6, M: 10, L: 10, XL: 5 },
    brand: "CozyGear",
    tags: ["sweatpants", "unisex", "casual"],
    weight: "600g",
    dimensions: {
      width: "340mm",
      height: "30mm",
      depth: "280mm",
    },
    origin: "Bangladesh",
    shelfLife: "N/A",
    isOrganic: false,
    bestseller: false,
    discount: 7,
    inStock: true,
    stockQuantity: 31,
    unit: "pcs",
    date: 1705276800000,
  },
];

export const userData = [
  {
    name: "John Doe",
    email: "john@example.com",
    password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36P4/laSi", // bcrypt hash of "password123"
    cartData: {},
  },
  {
    name: "Jane Smith",
    email: "jane@example.com",
    password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36P4/laSi", // bcrypt hash of "password123"
    cartData: {
      product3: 1,
    },
  },
  {
    name: "Mike Johnson",
    email: "mike@example.com",
    password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36P4/laSi", // bcrypt hash of "password123"
    cartData: {},
  },
  {
    name: "Sarah Williams",
    email: "sarah@example.com",
    password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36P4/laSi", // bcrypt hash of "password123"
    cartData: {
      product4: 3,
      product5: 1,
    },
  },
  {
    name: "Admin User",
    email: "admin@forever.com",
    password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36P4/laSi", // bcrypt hash of "password123"
    cartData: {},
  },
];

export const orderData = [
  {
    userId: "user1_id_here",
    items: [
      { productId: "product1_id", quantity: 2, price: 29.99 },
      { productId: "product2_id", quantity: 1, price: 49.99 },
    ],
    amount: 109.97,
    address: {
      firstName: "John",
      lastName: "Doe",
      email: "john@example.com",
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zipcode: "10001",
      country: "USA",
      phone: "555-0123",
    },
    status: "Order Placed",
    paymentMethod: "Card",
    payment: true,
    date: new Date(),
  },
  {
    userId: "user2_id_here",
    items: [{ productId: "product3_id", quantity: 1, price: 24.99 }],
    amount: 24.99,
    address: {
      firstName: "Jane",
      lastName: "Smith",
      email: "jane@example.com",
      street: "456 Oak Avenue",
      city: "Los Angeles",
      state: "CA",
      zipcode: "90001",
      country: "USA",
      phone: "555-0456",
    },
    status: "Processing",
    paymentMethod: "Card",
    payment: true,
    date: new Date(),
  },
  {
    userId: "user3_id_here",
    items: [{ productId: "product4_id", quantity: 1, price: 39.99 }],
    amount: 39.99,
    address: {
      firstName: "Mike",
      lastName: "Johnson",
      email: "mike@example.com",
      street: "789 Pine Road",
      city: "Chicago",
      state: "IL",
      zipcode: "60601",
      country: "USA",
      phone: "555-0789",
    },
    status: "Shipped",
    paymentMethod: "Card",
    payment: true,
    date: new Date(),
  },
];

// Passwords used in userData (for reference):
// email: john@example.com, password: password123
// email: jane@example.com, password: password123
// email: mike@example.com, password: password123
// email: sarah@example.com, password: password123
// email: admin@forever.com, password: password123
